/*
 * ADC_Config.h
 *
 *  Created on: Aug 11, 2024
 *      Author: ZBook G3
 */

#ifndef MCAL_ADC_ADC_CONFIG_H_
#define MCAL_ADC_ADC_CONFIG_H_
// OPTION LEFT_ADJUST OR RIGHT_ADJUST
#define ADC_ADJUST_RESULT RIGHT_ADJUST

//OPTION AREF AVCC INTERNAL_2.56V
#define ADC_REFERNCE_SELECTION AREF

//OPTION PRE_DIV_BY_2  - PRE_DIV_BY_4 - 8 - 16 - 32 - 64 - 128
#define ADC_PRESCALER_VALUE		PRE_DIV_BY_128

// ENABLING ADC OR NOT
#define ADC_ENABLE ENABLE
#endif /* MCAL_ADC_ADC_CONFIG_H_ */
